name: "Compute Feature Name"
description: "Build a safe feature environment name from extracted name (e.g., dashboard-pr.123 -> dashboard-pr-123)"
inputs:
  prefix:
    description: "Prefix to prepend to the feature name"
    required: true
outputs:
  feature_name:
    description: "Sanitized feature name"
    value: ${{ steps.mk.outputs.feature_name }}
runs:
  using: "composite"
  steps:
    - name: Compute name from ref
      id: name
      uses: ./.github/actions/ompute-name-from-ref

    - name: Make feature name
      id: mk
      shell: bash
      run: |
        set -euo pipefail
        NAME="${{ steps.name.outputs.name }}"
        PREFIX="${{ inputs.prefix }}"
        echo "feature_name=$PREFIX$NAME" | sed 's:\.:-:g' >> $GITHUB_OUTPUT