name: PR Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    name: Destroy Stack
    uses: webgains/github-workflows/.github/workflows/destroy-stack.yml@main
    secrets: inherit
    with:
      environment: feature
      stack: superset-pr-${{ github.event.pull_request.number }}SupersetService
    permissions:
      contents: read
      deployments: write
      id-token: write
