name: PR Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: superset-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write
  deployments: write
  id-token: write
  packages: read
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    name: Build
    secrets: inherit
    permissions:
      checks: write
      actions: write
      contents: write
      packages: read
      issues: read
      pull-requests: write
      id-token: write

  labels:
    runs-on: ubuntu-latest
    name: Add Labels
    steps:
      - name: Add labels
        id: add_labels
        run: |
          echo "feature_name=superset-pr-${{ github.event.pull_request.number }}" | sed 's:\.:-:g' >> $GITHUB_OUTPUT
    outputs:
      feature_name: ${{ steps.add_labels.outputs.feature_name }}

  deploy:
    name: Deploy to Dev Environment
    needs: [labels, build]
    uses: ./.github/workflows/deploy-service-to-environment.yml
    secrets: inherit
    with:
      environment: dev
      name: ${{ needs.labels.outputs.feature_name }}
      stack: ${{ needs.labels.outputs.feature_name }}
      service: superset
      component: service
      override: |
        {
          "namespace": "${{ needs.labels.outputs.feature_name }}",
          "supersetImageTag": "${{ needs.build.outputs.tag_hash }}"
        }
    permissions:
      actions: read
      contents: read
      deployments: write
      id-token: write
      packages: read
